### ISSUE TITLE
zou hier een  borderradius kunnen komen

### ISSUE THREAD

**Issue by Theo-denBlanken** [EdgeworthWright/Sass_PP#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
  .CTA
    font-size: 18px
    font-weight: bold
    margin: 5em 5em 2em 17em 
```

URL: https://github.com/EdgeworthWright/Sass_PP/blob/master/sass/_header.sass

Feedback: Daar zijn wel prefixes voor nodig[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"cc2689fd4b7df5e5bd85fa5b4968ca4fc7666923","path":"sass/_header.sass","reviewer":"Theo-denBlanken"}')

**Comment by EdgeworthWright** [comment]
Gedaan.
